title: Glenn Finds Tech
url: "https://glennfindstech.com"
baseurl: "/"

markdown: kramdown

remote_theme: ankitsultana/researcher@gem

ins_logo: "./icon.png"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "About"
    link: "/about/"
